version: 2.1
orbs:
  qlty: qltysh/qlty-orb@0.1.0
jobs:
  default: &default
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run: ruby --version && bundle check || bundle install
      - run:
          command: bundle exec rake
      - store_test_results:
          path: test-results
  test-3-1:
    <<: *default
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run: bundle check || bundle install
      - run:
          command: |
            bundle exec rake RUBYOPT='--enable-frozen-string-literal --debug-frozen-string-literal'
      - store_test_results:
          path: test-results
      - qlty/coverage_publish:
          files: coverage/coverage.json
  test-3-2:
    <<: *default
    docker:
      - image: cimg/ruby:3.2
  test-3-4:
    <<: *default
    docker:
      - image: cimg/ruby:3.4
workflows:
  version: 2
  tests:
    jobs:
      - default
      - test-3-1
      - test-3-2
      - test-3-4
